### PR TITLE
Fixes to issues #1 and #2, and fix APNS payload values

### PR DESCRIPTION
**Pull request by dsyrstad**
This fixes issues #1 and #2, and fixes APNS payload values. At minimum, the APNS payload requires an `aps` key with an object value.

The print statements on #1 were causing issues with my server logging.

I also:
- made fixes to `.gitignore` and removed pubspec.lock to make it conform to a standard Dart package project.
- Upgraded to support Dart 3.0+.
- Fixed commenting - replacing `///` with `//` where appropriate.
- Support Webpush `fcm_options` and support proper `notification` object.

### CODE REVIEW

**Comment by OttomanDeveloper** [comment]
Thank you for your contribution

**Comment by dsyrstad** [comment]
@OttomanDeveloper Thanks for the merge! Will you be publishing a new version to pub.dev?

**Comment by OttomanDeveloper** [comment]
Yes, Tomorrow hopefully

**Comment by OttomanDeveloper** [comment]
Update is Live on Pub.dev

**Pull request merged**
